name: configure-build-run
on: 
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository to checkout'
        required: false
        type: string
      commit_back:
        type: boolean
        description: 'Commit README and summary file back to repo (needed by dashboard repo)'
        required: false
        default: false
  workflow_call:
    inputs:
      repository:
        description: 'The repository to checkout'
        required: false
        type: string
      commit_back:
        type: boolean
        description: 'Commit README and summary file back to repo (needed by dashboard repo)'
        required: false
        default: false

jobs:

  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.set-matrix.outputs.matrix_json }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: ${{ inputs.repository || github.repository }}
          submodules: 'recursive'
      - id: set-matrix
        run: |
          PROJECT_DIRS=$(ls -d */ | sed 's/\///g')  # Assuming each directory is a project
          MATRIX=()

          # Check for CMakeLists.txt in the current directory
          if [[ -f "CMakeLists.txt" ]]; then
            MATRIX+=("{\"project_dir\":\"\", \"geant4_version\":\"11.1.p02\", \"platform\":\"centos7\", \"gcc_version\":\"10\"}")
            MATRIX+=("{\"project_dir\":\"\", \"geant4_version\":\"10.7.p03\", \"platform\":\"centos7\", \"gcc_version\":\"10\"}")
            MATRIX+=("{\"project_dir\":\"\", \"geant4_version\":\"11.1.ref10\", \"platform\":\"centos8\", \"gcc_version\":\"10\"}")
          fi

          for DIR in $PROJECT_DIRS; do
            # Check for CMakeLists.txt in the directory
            if [[ -f "$DIR/CMakeLists.txt" ]] || [[ -n $(find "$DIR" -maxdepth 1 -type f -name "CMakeLists.txt") ]]; then
              MATRIX+=("{\"project_dir\":\"$DIR\", \"geant4_version\":\"11.1.p02\", \"platform\":\"centos7\", \"gcc_version\":\"10\"}")
              MATRIX+=("{\"project_dir\":\"$DIR\", \"geant4_version\":\"10.7.p03\", \"platform\":\"centos7\", \"gcc_version\":\"10\"}")
              MATRIX+=("{\"project_dir\":\"$DIR\", \"geant4_version\":\"11.1.ref10\", \"platform\":\"centos8\", \"gcc_version\":\"10\"}")
            fi
          done

          # Convert array to JSON string
          # MATRIX_JSON="["
          MATRIX_JSON="{\"include\":["
          for i in "${!MATRIX[@]}"; do
            MATRIX_JSON+="${MATRIX[$i]}"
            if [ $((i+1)) -lt ${#MATRIX[@]} ]; then
              MATRIX_JSON+=","
            fi
          done
          MATRIX_JSON+="]}"
          #MATRIX_JSON+="]"

          # Print the matrix
          echo "Matrix JSON: $MATRIX_JSON"

          # Set the output for GitHub Actions
          echo "matrix_json<<EOF" >> $GITHUB_OUTPUT
          echo "$MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-and-test:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false  # This prevents other jobs from being canceled if one fails
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix_json)}}
#      matrix:
#        include:
#          - geant4_version: "11.1.p02"
#            platform: "centos7" 
#            gcc_version: "10" 
#          - geant4_version: "10.7.p03"
#            platform: "centos7"
#            gcc_version: "10"
#          - geant4_version: "11.1.ref10"
#            platform: "centos8"
#            gcc_version: "10"
       
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: ${{ inputs.repository || github.repository }}
          submodules: 'recursive'
      - uses: cvmfs-contrib/github-action-cvmfs@v3
      - name: Use Matrix JSON
        run: |
          echo "${{needs.prepare-matrix.outputs.matrix_json}}"
      - name: Start container
        run: |
          CONTAINER_NAME=my-container-${{ github.run_id }}-${{ github.run_number }}
          docker run -id --name $CONTAINER_NAME \
            --volume "${{ github.workspace }}:/workspace" \
            --volume /cvmfs:/cvmfs:shared \
            --workdir /workspace \
            ghcr.io/aidasoft/${{ matrix.platform }}:latest /bin/bash
          echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
      - name: Connect to container and configure G4 app
        id: configure-app
        run: |
          docker exec $CONTAINER_NAME /bin/bash -c "set -o pipefail; \
          export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.26.2/Linux-x86_64/bin/:${PATH} && \
          source /cvmfs/geant4.cern.ch/geant4/${{ matrix.geant4_version }}/x86_64-${{ matrix.platform }}-gcc${{ matrix.gcc_version }}-optdeb/bin/geant4.sh && \
          source /cvmfs/sft.cern.ch/lcg/contrib/gcc/${{ matrix.gcc_version }}/x86_64-${{ matrix.platform }}/setup.sh && \
          mkdir -p build logs install && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install ../${{matrix.project_dir}}/ 2>&1 | \
          tee /workspace/logs/${{matrix.project_dir}}-stderr-configure-${{ matrix.geant4_version }}.log"
      - name: Connect to container and build G4 app
        id: build-app
        run: |
          docker exec $CONTAINER_NAME /bin/bash -c "set -o pipefail; \
          export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.26.2/Linux-x86_64/bin/:${PATH} && \
          source /cvmfs/geant4.cern.ch/geant4/${{ matrix.geant4_version }}/x86_64-${{ matrix.platform }}-gcc${{ matrix.gcc_version }}-optdeb/bin/geant4.sh && \
          source /cvmfs/sft.cern.ch/lcg/contrib/gcc/${{ matrix.gcc_version }}/x86_64-${{ matrix.platform }}/setup.sh && \
          cd build && make install 2>&1 | \
          tee /workspace/logs/${{matrix.project_dir}}-stderr-build-${{ matrix.geant4_version }}.log"   
      - name: Run quick app tests.
        run: |
          docker exec $CONTAINER_NAME /bin/bash -c "set -o pipefail; \
          export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.26.2/Linux-x86_64/bin/:${PATH} && \
          source /cvmfs/geant4.cern.ch/geant4/${{ matrix.geant4_version }}/x86_64-${{ matrix.platform }}-gcc${{ matrix.gcc_version }}-optdeb/bin/geant4.sh && \
          source /cvmfs/sft.cern.ch/lcg/contrib/gcc/${{ matrix.gcc_version }}/x86_64-${{ matrix.platform }}/setup.sh && \
          cd build | \
          tee /workspace/logs/${{matrix.project_dir}}-stderr-run-${{ matrix.geant4_version }}.log"  
          executable=$(docker exec $CONTAINER_NAME /bin/bash -c "find . -maxdepth 1 -type f -executable -exec file -i '{}' \; | grep 'x-executable; charset=binary' | cut -d ':' -f 1 | sed 's|^\./||'") 
          echo "executable=${executable}" >> $GITHUB_ENV
          echo "executable=${executable}"
      - name: Find and set executable
        run: |
          executable=$(docker exec $CONTAINER_NAME /bin/bash -c "find build -maxdepth 1 -type f -executable -exec file -i '{}' \; | grep 'x-executable; charset=binary' | cut -d ':' -f 1 | sed 's|^build/||'")
          echo "executable=${executable}" >> $GITHUB_ENV
      - name: Upload failure log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.project_dir}}-logfiles-${{ matrix.geant4_version }}.log
          path: logs/*.log
      - name: Generate YAML file
        if: always() && inputs.commit_back
        run: |
          echo "  - name: \"${{ matrix.project_dir }}\"" >> results.yaml
          echo "    geant4_versions:" >> results.yaml
          echo "      - version: \"${{ matrix.geant4_version }}\"" >> results.yaml
          echo "        compilers:" >> results.yaml
          echo "          - compiler_version: \"${{ matrix.gcc_version }}\"" >> results.yaml
          echo "            results:" >> results.yaml
          echo "              configure: \"${{ steps.configure-app.outcome }}\"" >> results.yaml
          echo "              build: \"${{ steps.build-app.outcome }}\"" >> results.yaml
          echo "              executable: \"${executable}\"" >> results.yaml
          cp results.yaml ${{matrix.project_dir}}-${{ matrix.geant4_version }}-results.yaml
      - name: Check content of YAML file
        if: always() && inputs.commit_back
        run: |
          cat results.yaml
      - name: Upload result file
        if: always() && inputs.commit_back
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.project_dir}}-${{ matrix.geant4_version }}-results.yaml
          path: ${{matrix.project_dir}}-${{ matrix.geant4_version }}-results.yaml    

  collect-results:
    if: always() && inputs.commit_back
    needs: build-and-test
    runs-on: ubuntu-latest
         
    steps: 
      - uses: actions/checkout@v4
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}    
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display Current Directory
        run: pwd
      - run: |   
          pwd
          ls -la  
          echo "tests:" > results_ci.yaml
          cat *-results.yaml/*results*.yaml >> results_ci.yaml
          python3 run-yaml.py > results.MD
          python3 run-yaml-fancy.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add results_ci.yaml results.MD output.md
          git commit -m "Add new CI results in YAML format and MD file" results_ci.yaml results.MD output.md
          git push  
          
#      - uses: EndBug/add-and-commit@v9
#        with:
#          message: 'Add the very useful text file'
#          add: 'TestEm3-logfiles-10.7.p03.log/TestEm3-stderr-build-10.7.p03.log --force'


    
